### ISSUE TITLE
Bluetooth keyboard support

### ISSUE THREAD

**Issue by brockelmore** [ItayGarin/ktrl#11]
It would be great to have bluetooth keyboard support. On arch + Xorg, at least, this is what the wiki says:
```
Xorg
Device should be added as `/dev/input/event*` and your Xorg should add it automatically if you did not disable such feature. 
```

And the corresponding events:
```
/dev/input/event0   /dev/input/event11  /dev/input/event14  /dev/input/event17  /dev/input/event2   /dev/input/event22  /dev/input/event25  /dev/input/event4  /dev/input/event7
/dev/input/event1   /dev/input/event12  /dev/input/event15  /dev/input/event18  /dev/input/event20  /dev/input/event23  /dev/input/event26  /dev/input/event5  /dev/input/event8
/dev/input/event10  /dev/input/event13  /dev/input/event16  /dev/input/event19  /dev/input/event21  /dev/input/event24  /dev/input/event3   /dev/input/event6  /dev/input/event9
```

If you know a workaround, would love to know!

**Comment by ItayGarin** [comment]
Hey @brockelmore!
It's awesome to see you'd like to try out ktrl :)

I haven't tested Bluetooth keyboard support as I don't have one haha. But it should work!

It's just a matter of finding the correct input device. Try to look for a device with the '-kbd' suffix under `/dev/input/by-id` or `/dev/input/by-path`. 

If you have multiple devices with this suffix, just try them one by one until you find the right one.

If you that doesn't work. Please attach the contents of the by-id and by-path directories and I'll try to help! 😊

Let me know how it works out for you, and feel free to reach out with any other questions 😃

**Comment by brockelmore** [comment]
Here is my `/dev/input/by-id`:
```
usb-Logitech_USB_Receiver-event-if01      usb-Logitech_USB_Receiver-if02-event-mouse
usb-Logitech_USB_Receiver-if02-event-kbd  usb-Logitech_USB_Receiver-if02-mouse
```
and `by-path`:
```
pci-0000:07:00.1-usb-0:6.1:1.1-event        pci-0000:07:00.1-usb-0:6.1:1.2-mouse
pci-0000:07:00.1-usb-0:6.1:1.2-event-kbd    platform-pcspkr-event-spkr
pci-0000:07:00.1-usb-0:6.1:1.2-event-mouse
```
I am currently using a bluetooth apple keyboard. Tried the logitech one, but as I expected, it didn't work as it is just a usb receiver for all kinds of Logitech devices.

If you run: `cat /proc/bus/input/devices`, you get outputs like this:
```
I: Bus=0005 Vendor=05ac Product=0239 Version=0050
N: Name="Brock Elmore’s Keyboard"
P: Phys=<key boards mac addr>
S: Sysfs=/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.3/usb3/3-5/3-5:1.0/bluetooth/hci0/hci0:512/0005:05AC:0239.0009/input/input40
U: Uniq=<bluetooth controller addr>
H: Handlers=sysrq kbd event25 leds
B: PROP=0
B: EV=120013
B: KEY=10000 0 0 0 1007b00011007 ff9f217ac14057ff ffbeffdfffefffff fffffffffffffffe
B: MSC=10
B: LED=1f
```

So I know it uses /dev/input/event25, but that gives me:
```
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
thread 'main' panicked at 'The device doesn't support any format!?: DeviceNotAvailable', /home/brock/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.11.0/src/engine.rs:147:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After running for a little while (it constantly fires return button when on), then if I press anything, it crashes with that error.

Edit: Obviously looking at the full backtrace, that was from sound not working. Didn't even really mean to have the sound on so its no longer crashing at start and may "Just work". Might update the instructions for finding keyboard via `cat /proc/bus/input/devices` if using bluetooth!
