### ISSUE TITLE
Expose perform commands via cli

### ISSUE THREAD

**Issue by brockelmore** [ItayGarin/ktrl#13]
It would be great to be able to activate a particular layer via a script. I.e. I use bspwm, and when I change focus between windows, I would like to be able to update what layer is active (effectively, this turns layers into user-definable mappings for applications). This could be done via sending a command by having ktrl see if there is a running instance for the device and executing basically any of the perform commands.

I.e. in firefox, I can't redefine keyboard shortcuts (*easily, i.e. without compiling firefox myself essentially). Its dumb. 

So I would like to have a firefox layer that maps the keyboard shortcuts I want to use to the unchangeable firefox ones, same with other apps I use.

**Comment by ItayGarin** [comment]
That's an awesome idea! Really liked it :smile: 
I've come to expect the same from i3.
I'll definitely add this to my to-dos :)

**Comment by ItayGarin** [comment]
I thought about another cool feature that would go nicely with this - 
It'd be nice if ktrl exposed the layer state for external use. 
E.g We could use that the display the current active layers in i3/bspwn's bar.

Let me know what you think

**Comment by brockelmore** [comment]
Yeah that would be great to expose it. Integrates nicely with named layers obviously

**Comment by ItayGarin** [comment]
Implemented (under the "ipc" feature flag)
