### ISSUE TITLE
Named layers

### ISSUE THREAD

**Issue by brockelmore** [ItayGarin/ktrl#14]
It would be great to be able to name layers so if #13 gets integrated, you could activate via name. Also just helps for complex configs

**Comment by ItayGarin** [comment]
Yup. Great idea again :+1: 
What do you think of something like this -

```
(
    tap_hold_wait_time: ...,
    tap_dance_wait_time: ...,
    layer_aliases: {
        0: "base",
        1: "firefox",
        2: "vim",
        13: "not-all-layers-most-have-aliases",
    },
    layers: [
    ],
)
```

**Comment by brockelmore** [comment]
Brilliant, great way to do that. I can take a crack at implementation if you would like
