### ISSUE TITLE
Issue with ktrl service while running SELinux

### ISSUE THREAD

**Issue by ghost** [ItayGarin/ktrl#24]
I created a service based on `ktrl.service` found in the project's `etc` directory.

/etc/systemd/system/ktrl.service
```
[Unit]
Description=ktrl

[Service]
User=ktrl
Environment=HOME=/opt/ktrl
ExecStart=/home/andrew/.cargo/bin/ktrl -d /dev/input/event3
  
[Install]
WantedBy=multi-user.target
```
However, when I try to run the service I get the following error from `systemctl status ktrl.service`
```
     Loaded: loaded (/etc/systemd/system/ktrl.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sat 2020-06-27 10:35:08 EDT; 5s ago
    Process: 23335 ExecStart=/home/andrew/.cargo/bin/ktrl -d /dev/input/event3 (code=exited, status=203/EXEC)
   Main PID: 23335 (code=exited, status=203/EXEC)
        CPU: 5ms

Jun 27 10:35:08 localhost.localdomain systemd[1]: Started ktrl.
Jun 27 10:35:08 localhost.localdomain systemd[23335]: ktrl.service: Failed to execute command: Permission denied
Jun 27 10:35:08 localhost.localdomain systemd[23335]: ktrl.service: Failed at step EXEC spawning /home/andrew/.cargo/bin/ktrl: Permission denied
Jun 27 10:35:08 localhost.localdomain systemd[1]: ktrl.service: Main process exited, code=exited, status=203/EXEC
Jun 27 10:35:08 localhost.localdomain systemd[1]: ktrl.service: Failed with result 'exit-code'.
```

I was able to track the issue down to SELinux. While SELinux is enforced the service does not work, however, while SELinux is disabled the service runs without issue. This is due to the bin being located in the user's home directory.

It would be better to have the bin located in `/usr/local/bin/ktrl` then you could update the ktrl.service file to be

```
[Unit]
Description=ktrl

[Service]
User=ktrl
Environment=/opt/ktrl
ExecStart=/usr/local/bin/ktrl -d /dev/input/event3
  
[Install]
WantedBy=multi-user.target
```
That way there would be no issues with SELinux.

**Comment by ItayGarin** [comment]
Thanks for the report Andrew!
Always glad to hear more people are trying out ktrl 😊

Might be wrong here, but I don't think many user geared distros come with SELinux on. If that's the case, I think this is probably a low priority issue. 

Regardless, If you'd like to take a stab at fixing this, I'd happily accept your PR

**Comment by ghost** [comment]
Fedora has SELinux on by default and that's a fairly popular distro.

Regardless, I'll experiment with some solutions on Monday and if I find one that works I'll create a PR.

**Comment by ItayGarin** [comment]
Nice on Fedora! Had no idea haha
Looking forward to hear what you find. Thanks!
