### ISSUE TITLE
Cross platform would be cool

### ISSUE THREAD

**Issue by gilescope** [ItayGarin/ktrl#31]
currently we need to configure karibener for mac and autohot keys for windows as well as ktrl. When we use a laptop we are stuck with the keyboard we have (otherwise QMK or similar makes sense).

Is there some interest in cross platform support?

**Comment by ItayGarin** [comment]
Thanks for checking out ktrl @gilescope!
Unfortunately, porting ktrl to other platforms is a non-trivial task.
ktrl relies quite heavily on the way evdev events work on Linux.

Ofc, I'll gladly accept any PRs that tackle this :)
