### ISSUE TITLE
No Sound Effect variant

### ISSUE THREAD

**Issue by AckslD** [ItayGarin/ktrl#33]
I'm getting the error:
```
Failed to parse the config file: Error { code: Message("unknown variant `Sound`, expected one of `NoOp`, `Key`, `KeySticky`, `KeySeq`, `Meh`, `Hyper`, `ActivateProfile`, `DeactivateProfile`, `DeactivateAllProfiles`, `TurnOnLayer`, `TurnOffLayer`, `ToggleLayer`, `TurnOnLayerAlias`, `TurnOffLayerAlias`, `ToggleLayerAlias`, `MomentaryLayer`, `Multi`")
```
Not sure why `Sound` is not a variant.

I installed `ktrl` using cargo and am on version 0.1.7

**Comment by ItayGarin** [comment]
Hey Axel! Thanks for checking out ktrl :)
You'd need to enable the [`sound` feature](https://github.com/ItayGarin/ktrl/blob/master/Cargo.toml#L32) when installing via cargo (`--features`).

Though I must admit I haven't used that feature for quite some time, and the last time I checked it was a bit buggy. 
You're welcome to try it out and report back haha

**Comment by AckslD** [comment]
Thanks for the quick reply @ItayGarin! :) That indeed worked and the feature seems to be working fine :+1:
